fix: solving exception with map function (#113) this commit should improve the search, since the extension was crashing with certain searches. Now I fixed the issue: Exception in callback for signal: TypeError: prefix_results.map is not a function